# Grid size
CELL_SIZE = 24
GRID_ROWS = 28
GRID_COLUMNS = 33
SCREEN_WIDTH = GRID_COLUMNS * CELL_SIZE  # 792 pixels
SCREEN_HEIGHT = GRID_ROWS * CELL_SIZE # 672 pixels


ROW_MARGIN = (SCREEN_WIDTH - (CELL_SIZE * GRID_COLUMNS)) / 2
COLUMN_MARGIN = (SCREEN_HEIGHT - (CELL_SIZE * GRID_ROWS)) / 2

MAZE_GRID_ROWS = GRID_ROWS - 2
MAZE_GRID_COLUMNS = GRID_COLUMNS

MAZE_LEVEL_START_X = (-SCREEN_WIDTH / 2) + ROW_MARGIN + CELL_SIZE / 2
MAZE_LEVEL_START_Y = (SCREEN_HEIGHT / 2) - COLUMN_MARGIN - (CELL_SIZE * 5 / 2)

# Pac-Man Parameters
PLAYER_MOVE_SPEED = 2  
SCORE_PER_PELLET = 10  

# Enemy Parameters
ENEMY_NUMBER = 4       # Số lượng Ghost
ENEMY_MOVE_SPEED = 2   
ENEMY_RADAR = CELL_SIZE * 5
